import pytest
from playwright.sync_api import Page, Playwright
from _pytest.fixtures import SubRequest
from pages.authentication.registration_page import RegistrationPage
from tools.playwright.pages import initialize_playwright_page
from config import settings
from tools.routes import AppRoute


@pytest.fixture(params=settings.browsers)
def chromium_page(request: SubRequest, playwright: Playwright) -> Page:
    """
    Provides a fresh Playwright Page instance for UI testing.
    Parameterized to run across all browsers defined in settings.
    """
    yield from initialize_playwright_page(
        playwright,
        test_name=request.node.name,
        browser_type=request.param
    )

@pytest.fixture(scope="session")
def initialize_browser_state(playwright: Playwright):
    """
    Session-scoped fixture that prepares an authenticated browser state.
    
    It launches a browser, registers a test user, saves the storage state 
    (cookies, local storage) to a file, and closes the browser. This file is 
    then used by other fixtures to skip the login step in tests.
    """
    browser = playwright.chromium.launch(headless=settings.headless)
    context = browser.new_context(base_url=settings.get_base_url())
    page = context.new_page()
    registration_page = RegistrationPage(page=page)
    registration_page.visit(AppRoute.REGISTRATION)
    registration_page.registration_form.fill(
        email=settings.test_user.email,
        username=settings.test_user.username,
        password=settings.test_user.password
    )
    registration_page.click_registration_button()
    context.storage_state(path=settings.browser_state_file)
    browser.close()


@pytest.fixture(params=settings.browsers)
def chromium_page_with_state(initialize_browser_state, request: SubRequest, playwright: Playwright) -> Page:
    """
    Provides a Playwright Page instance that is already authenticated.
    
    Loads the session state generated by `initialize_browser_state`, 
    allowing tests to bypass the login screen and start directly on protected routes.
    """
    yield from initialize_playwright_page(
        playwright,
        test_name=request.node.name,
        browser_type=request.param,
        storage_state=settings.browser_state_file
    )